### ISSUE TITLE
cli support

### ISSUE THREAD

**Issue by jjhesk** [timdream/wordfreq#9]
what is the sample code for running this childprocess in nodejs.
let say i have a block of string in txt;
```js
var content = "...about 900kb";


```

what do i need to do? @timdream

**Comment by timdream** [comment]
Why would you need to run it inside a content process? Just `require()` the sync version of the library into your NodeJS code and use it.

The cli script does exactly the same thing, starting reading from [here](https://github.com/timdream/wordfreq/blob/1f98a9f270008a0d372247ef3940abeb37466408/src/wordfreq.cli.js#L45).
